package com.uptc.views;

public enum Options{
    NEW_STATE,NEW_TRANSITION,DELETE_STATE,DELETE_TRANSITION,MINIMIZATE,VALIDATE_WORD,
    INITIAL_STATE,FINAL_STATE,CANCEL,VALIDATE,CLOSE,STEP,STEP_BY_STATE;
}

